### ISSUE TITLE
Creating graphs in code

### ISSUE THREAD

**Issue by alldritt** [nmandica/DirectedGraph#6]
I'm trying to grate a graph in code rather than loading it from a file as the sample app does and I'm finding I cannot declare instances of SimpleGraph and pass arrays of SimpleEdge and SimpleNode instances as there is no initializer for this.  Can you show how I can do this?

Here's what I'm trying and I cannot seem to create an extension to Simple graph that offers the initializer I need:

```
import SwiftUI
import DirectedGraph


extension SimpleGraph {
    
    init(nodes: [SimpleNode], edges: [SimpleEdge]) {
        self.nodes = nodes
        self.edges = edges
    }
}

struct ContentView: View {
    
    var viewModel: GraphViewModel<SimpleGraph> {
        let nodes: [SimpleNode] = [SimpleNode(id: "1", group: 1),
                                   SimpleNode(id: "2", group: 1)]
        let edges: [SimpleEdge] = [SimpleEdge(source: "1", target: "2", value: 4)]
        let graph = SimpleGraph(nodes: nodes, edges: edges)
        
        return GraphViewModel(graph)
    }
    
    var body: some View {
        VStack {
            GraphView(viewModel)
        }
        .padding()
    }
}
```

**Comment by nmandica** [comment]
Does the [latest release](https://github.com/nmandica/DirectedGraph/releases/tag/0.2.5) fix your problem ?

**Comment by alldritt** [comment]
Perfect, thank you!
